package com.admin.mapper.finance;

import org.apache.ibatis.annotations.Param;

import com.admin.model.finance.YqzlXfer;


public interface YqzlXferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqzl_xfer
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqzl_xfer
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    int insert(YqzlXfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqzl_xfer
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    int insertSelective(YqzlXfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqzl_xfer
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    YqzlXfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqzl_xfer
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    int updateByPrimaryKeySelective(YqzlXfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yqzl_xfer
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    int updateByPrimaryKey(YqzlXfer record);
    
    int selectCountByOrderIdAndState(@Param("orderId") Integer orderId,@Param("state") Integer state);
    
    int selectCountByPaymentIdAndState(@Param("paymentId") Integer paymentId,@Param("state") Integer state);
}