package com.admin.model.finance;

import java.util.Date;

public class DirectPurchaseCoachesPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.id
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.coachesId
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Integer coachesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.price
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.bankAccount
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Integer bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.type
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.payTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.createTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.updateTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DirectPurchaseCoachesPayment.status
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.id
     *
     * @return the value of DirectPurchaseCoachesPayment.id
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.id
     *
     * @param id the value for DirectPurchaseCoachesPayment.id
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.coachesId
     *
     * @return the value of DirectPurchaseCoachesPayment.coachesId
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Integer getCoachesId() {
        return coachesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.coachesId
     *
     * @param coachesId the value for DirectPurchaseCoachesPayment.coachesId
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setCoachesId(Integer coachesId) {
        this.coachesId = coachesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.price
     *
     * @return the value of DirectPurchaseCoachesPayment.price
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.price
     *
     * @param price the value for DirectPurchaseCoachesPayment.price
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.bankAccount
     *
     * @return the value of DirectPurchaseCoachesPayment.bankAccount
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Integer getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.bankAccount
     *
     * @param bankAccount the value for DirectPurchaseCoachesPayment.bankAccount
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setBankAccount(Integer bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.type
     *
     * @return the value of DirectPurchaseCoachesPayment.type
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.type
     *
     * @param type the value for DirectPurchaseCoachesPayment.type
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.payTime
     *
     * @return the value of DirectPurchaseCoachesPayment.payTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.payTime
     *
     * @param payTime the value for DirectPurchaseCoachesPayment.payTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.createTime
     *
     * @return the value of DirectPurchaseCoachesPayment.createTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.createTime
     *
     * @param createTime the value for DirectPurchaseCoachesPayment.createTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.updateTime
     *
     * @return the value of DirectPurchaseCoachesPayment.updateTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.updateTime
     *
     * @param updateTime the value for DirectPurchaseCoachesPayment.updateTime
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DirectPurchaseCoachesPayment.status
     *
     * @return the value of DirectPurchaseCoachesPayment.status
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DirectPurchaseCoachesPayment.status
     *
     * @param status the value for DirectPurchaseCoachesPayment.status
     *
     * @mbggenerated Fri Jul 22 14:38:25 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}