package com.admin.model.finance;

import java.util.Date;

public class YqzlXfer {
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.id
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.orderId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer orderid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.paymentId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer paymentId;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.trnId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String trnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.insId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.acntNo
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String acntno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.acntName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String acntname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.acntToNo
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String acnttono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.acntToName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String acnttoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.externBank
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String externbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.localFlag
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String localflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.rcvCustType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String rcvcusttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.bankCode
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.bankName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.bankAddr
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String bankaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.areaCode
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.amount
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.explains
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String explains;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.state
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.message
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.transferTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Date transfertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.createTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.updateTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.type
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.payType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.totalRow
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer totalrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.totalAmt
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String totalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.batchLocalFlag
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String batchlocalflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.certificateId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String certificateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.batchRcvCustType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String batchrcvcusttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.batchSms
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private Integer batchsms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yqzl_xfer.batchPhone
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    private String batchphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.id
     *
     * @return the value of yqzl_xfer.id
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.id
     *
     * @param id the value for yqzl_xfer.id
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.orderId
     *
     * @return the value of yqzl_xfer.orderId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.orderId
     *
     * @param id the value for yqzl_xfer.orderId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.trnId
     *
     * @return the value of yqzl_xfer.trnId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getTrnid() {
        return trnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.trnId
     *
     * @param trnid the value for yqzl_xfer.trnId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setTrnid(String trnid) {
        this.trnid = trnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.insId
     *
     * @return the value of yqzl_xfer.insId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.insId
     *
     * @param insid the value for yqzl_xfer.insId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setInsid(String insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.acntNo
     *
     * @return the value of yqzl_xfer.acntNo
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getAcntno() {
        return acntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.acntNo
     *
     * @param acntno the value for yqzl_xfer.acntNo
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setAcntno(String acntno) {
        this.acntno = acntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.acntName
     *
     * @return the value of yqzl_xfer.acntName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getAcntname() {
        return acntname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.acntName
     *
     * @param acntname the value for yqzl_xfer.acntName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setAcntname(String acntname) {
        this.acntname = acntname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.acntToNo
     *
     * @return the value of yqzl_xfer.acntToNo
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getAcnttono() {
        return acnttono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.acntToNo
     *
     * @param acnttono the value for yqzl_xfer.acntToNo
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setAcnttono(String acnttono) {
        this.acnttono = acnttono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.acntToName
     *
     * @return the value of yqzl_xfer.acntToName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getAcnttoname() {
        return acnttoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.acntToName
     *
     * @param acnttoname the value for yqzl_xfer.acntToName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setAcnttoname(String acnttoname) {
        this.acnttoname = acnttoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.externBank
     *
     * @return the value of yqzl_xfer.externBank
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getExternbank() {
        return externbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.externBank
     *
     * @param externbank the value for yqzl_xfer.externBank
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setExternbank(String externbank) {
        this.externbank = externbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.localFlag
     *
     * @return the value of yqzl_xfer.localFlag
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getLocalflag() {
        return localflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.localFlag
     *
     * @param localflag the value for yqzl_xfer.localFlag
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setLocalflag(String localflag) {
        this.localflag = localflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.rcvCustType
     *
     * @return the value of yqzl_xfer.rcvCustType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getRcvcusttype() {
        return rcvcusttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.rcvCustType
     *
     * @param rcvcusttype the value for yqzl_xfer.rcvCustType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setRcvcusttype(String rcvcusttype) {
        this.rcvcusttype = rcvcusttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.bankCode
     *
     * @return the value of yqzl_xfer.bankCode
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.bankCode
     *
     * @param bankcode the value for yqzl_xfer.bankCode
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.bankName
     *
     * @return the value of yqzl_xfer.bankName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.bankName
     *
     * @param bankname the value for yqzl_xfer.bankName
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.bankAddr
     *
     * @return the value of yqzl_xfer.bankAddr
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getBankaddr() {
        return bankaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.bankAddr
     *
     * @param bankaddr the value for yqzl_xfer.bankAddr
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setBankaddr(String bankaddr) {
        this.bankaddr = bankaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.areaCode
     *
     * @return the value of yqzl_xfer.areaCode
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.areaCode
     *
     * @param areacode the value for yqzl_xfer.areaCode
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.amount
     *
     * @return the value of yqzl_xfer.amount
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.amount
     *
     * @param amount the value for yqzl_xfer.amount
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.explains
     *
     * @return the value of yqzl_xfer.explains
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getExplains() {
        return explains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.explains
     *
     * @param explains the value for yqzl_xfer.explains
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setExplains(String explains) {
        this.explains = explains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.state
     *
     * @return the value of yqzl_xfer.state
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.state
     *
     * @param state the value for yqzl_xfer.state
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.message
     *
     * @return the value of yqzl_xfer.message
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.message
     *
     * @param message the value for yqzl_xfer.message
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.transferTime
     *
     * @return the value of yqzl_xfer.transferTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Date getTransfertime() {
        return transfertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.transferTime
     *
     * @param transfertime the value for yqzl_xfer.transferTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setTransfertime(Date transfertime) {
        this.transfertime = transfertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.createTime
     *
     * @return the value of yqzl_xfer.createTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.createTime
     *
     * @param createtime the value for yqzl_xfer.createTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.updateTime
     *
     * @return the value of yqzl_xfer.updateTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.updateTime
     *
     * @param updatetime the value for yqzl_xfer.updateTime
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.type
     *
     * @return the value of yqzl_xfer.type
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.type
     *
     * @param type the value for yqzl_xfer.type
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.payType
     *
     * @return the value of yqzl_xfer.payType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.payType
     *
     * @param paytype the value for yqzl_xfer.payType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.totalRow
     *
     * @return the value of yqzl_xfer.totalRow
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Integer getTotalrow() {
        return totalrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.totalRow
     *
     * @param totalrow the value for yqzl_xfer.totalRow
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setTotalrow(Integer totalrow) {
        this.totalrow = totalrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.totalAmt
     *
     * @return the value of yqzl_xfer.totalAmt
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getTotalamt() {
        return totalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.totalAmt
     *
     * @param totalamt the value for yqzl_xfer.totalAmt
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setTotalamt(String totalamt) {
        this.totalamt = totalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.batchLocalFlag
     *
     * @return the value of yqzl_xfer.batchLocalFlag
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getBatchlocalflag() {
        return batchlocalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.batchLocalFlag
     *
     * @param batchlocalflag the value for yqzl_xfer.batchLocalFlag
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setBatchlocalflag(String batchlocalflag) {
        this.batchlocalflag = batchlocalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.certificateId
     *
     * @return the value of yqzl_xfer.certificateId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getCertificateid() {
        return certificateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.certificateId
     *
     * @param certificateid the value for yqzl_xfer.certificateId
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setCertificateid(String certificateid) {
        this.certificateid = certificateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.batchRcvCustType
     *
     * @return the value of yqzl_xfer.batchRcvCustType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getBatchrcvcusttype() {
        return batchrcvcusttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.batchRcvCustType
     *
     * @param batchrcvcusttype the value for yqzl_xfer.batchRcvCustType
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setBatchrcvcusttype(String batchrcvcusttype) {
        this.batchrcvcusttype = batchrcvcusttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.batchSms
     *
     * @return the value of yqzl_xfer.batchSms
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public Integer getBatchsms() {
        return batchsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.batchSms
     *
     * @param batchsms the value for yqzl_xfer.batchSms
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setBatchsms(Integer batchsms) {
        this.batchsms = batchsms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yqzl_xfer.batchPhone
     *
     * @return the value of yqzl_xfer.batchPhone
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public String getBatchphone() {
        return batchphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yqzl_xfer.batchPhone
     *
     * @param batchphone the value for yqzl_xfer.batchPhone
     *
     * @mbggenerated Fri Jun 17 10:21:42 CST 2016
     */
    public void setBatchphone(String batchphone) {
        this.batchphone = batchphone;
    }

	public Integer getPaymentId() {
		return paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}
    
    
    
}