package cn.umbrella.finance.mapper.alipay;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;
import cn.umbrella.finance.dataobject.alipay.AlipayPayTradeNo;


public class AlipayPayTradeNoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_pay_trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String insertSelective(AlipayPayTradeNo record) {
        BEGIN();
        INSERT_INTO("alipay_pay_trade_no");
        
        if (record.getOrderNum() != null) {
            VALUES("orderNum", "#{orderNum,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTradeNo() != null) {
            VALUES("out_trade_no", "#{outTradeNo,jdbcType=VARCHAR}");
        }
        
        if (record.getTradeNo() != null) {
            VALUES("trade_no", "#{tradeNo,jdbcType=VARCHAR}");
        }
        
        if (record.getSubject() != null) {
            VALUES("subject", "#{subject,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalFee() != null) {
            VALUES("total_fee", "#{totalFee,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            VALUES("gmt_create", "#{gmtCreate,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtPayment() != null) {
            VALUES("gmt_payment", "#{gmtPayment,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtClose() != null) {
            VALUES("gmt_close", "#{gmtClose,jdbcType=VARCHAR}");
        }
        
        if (record.getSellerEmail() != null) {
            VALUES("seller_email", "#{sellerEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getBuyerEmail() != null) {
            VALUES("buyer_email", "#{buyerEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getTradeStatus() != null) {
            VALUES("trade_status", "#{tradeStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getNotifyUrl() != null) {
            VALUES("notify_url", "#{notifyUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_pay_trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String updateByPrimaryKeySelective(AlipayPayTradeNo record) {
        BEGIN();
        UPDATE("alipay_pay_trade_no");
        
        if (record.getOrderNum() != null) {
            SET("orderNum = #{orderNum,jdbcType=VARCHAR}");
        }
        
        if (record.getTradeNo() != null) {
            SET("trade_no = #{tradeNo,jdbcType=VARCHAR}");
        }
        
        if (record.getSubject() != null) {
            SET("subject = #{subject,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalFee() != null) {
            SET("total_fee = #{totalFee,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("gmt_create = #{gmtCreate,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtPayment() != null) {
            SET("gmt_payment = #{gmtPayment,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtClose() != null) {
            SET("gmt_close = #{gmtClose,jdbcType=VARCHAR}");
        }
        
        if (record.getSellerEmail() != null) {
            SET("seller_email = #{sellerEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getBuyerEmail() != null) {
            SET("buyer_email = #{buyerEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getTradeStatus() != null) {
            SET("trade_status = #{tradeStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getNotifyUrl() != null) {
            SET("notify_url = #{notifyUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        WHERE("out_trade_no = #{outTradeNo,jdbcType=VARCHAR}");
        
        return SQL();
    }
}