package cn.umbrella.finance.dataobject.alipay;

import java.util.Date;

public class AlipayRefundNo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.id
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.batch_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.batch_num
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private String batchNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.out_trade_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.trade_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.refund_fee
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private String refundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.refund_date
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private String refundDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.refund_status
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.create_time
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_refund_no.update_time
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.id
     *
     * @return the value of alipay_refund_no.id
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.id
     *
     * @param id the value for alipay_refund_no.id
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.batch_no
     *
     * @return the value of alipay_refund_no.batch_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.batch_no
     *
     * @param batchNo the value for alipay_refund_no.batch_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.batch_num
     *
     * @return the value of alipay_refund_no.batch_num
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public String getBatchNum() {
        return batchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.batch_num
     *
     * @param batchNum the value for alipay_refund_no.batch_num
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setBatchNum(String batchNum) {
        this.batchNum = batchNum == null ? null : batchNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.out_trade_no
     *
     * @return the value of alipay_refund_no.out_trade_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.out_trade_no
     *
     * @param outTradeNo the value for alipay_refund_no.out_trade_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.trade_no
     *
     * @return the value of alipay_refund_no.trade_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.trade_no
     *
     * @param tradeNo the value for alipay_refund_no.trade_no
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.refund_fee
     *
     * @return the value of alipay_refund_no.refund_fee
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public String getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.refund_fee
     *
     * @param refundFee the value for alipay_refund_no.refund_fee
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setRefundFee(String refundFee) {
        this.refundFee = refundFee == null ? null : refundFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.refund_date
     *
     * @return the value of alipay_refund_no.refund_date
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public String getRefundDate() {
        return refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.refund_date
     *
     * @param refundDate the value for alipay_refund_no.refund_date
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setRefundDate(String refundDate) {
        this.refundDate = refundDate == null ? null : refundDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.refund_status
     *
     * @return the value of alipay_refund_no.refund_status
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.refund_status
     *
     * @param refundStatus the value for alipay_refund_no.refund_status
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.create_time
     *
     * @return the value of alipay_refund_no.create_time
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.create_time
     *
     * @param createTime the value for alipay_refund_no.create_time
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_refund_no.update_time
     *
     * @return the value of alipay_refund_no.update_time
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_refund_no.update_time
     *
     * @param updateTime the value for alipay_refund_no.update_time
     *
     * @mbggenerated Mon Apr 11 16:57:04 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}