package cn.umbrella.finance.dataobject.alipay;

import java.util.Date;

public class AlipayPayTradeNo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.id
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private Integer id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.orderNum
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.out_trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.subject
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.total_fee
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.gmt_create
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.gmt_payment
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String gmtPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.gmt_close
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String gmtClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.seller_email
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String sellerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.buyer_email
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String buyerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.trade_status
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.notify_url
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.create_time
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_pay_trade_no.update_time
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.id
     *
     * @return the value of alipay_pay_trade_no.id
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.id
     *
     * @param id the value for alipay_pay_trade_no.id
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.orderNum
     *
     * @return the value of alipay_pay_trade_no.orderNum
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.orderNum
     *
     * @param id the value for alipay_pay_trade_no.orderNum
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.out_trade_no
     *
     * @return the value of alipay_pay_trade_no.out_trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.out_trade_no
     *
     * @param outTradeNo the value for alipay_pay_trade_no.out_trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.trade_no
     *
     * @return the value of alipay_pay_trade_no.trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.trade_no
     *
     * @param tradeNo the value for alipay_pay_trade_no.trade_no
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.subject
     *
     * @return the value of alipay_pay_trade_no.subject
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.subject
     *
     * @param subject the value for alipay_pay_trade_no.subject
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.total_fee
     *
     * @return the value of alipay_pay_trade_no.total_fee
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.total_fee
     *
     * @param totalFee the value for alipay_pay_trade_no.total_fee
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setTotalFee(String totalFee) {
        this.totalFee = totalFee == null ? null : totalFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.gmt_create
     *
     * @return the value of alipay_pay_trade_no.gmt_create
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.gmt_create
     *
     * @param gmtCreate the value for alipay_pay_trade_no.gmt_create
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.gmt_payment
     *
     * @return the value of alipay_pay_trade_no.gmt_payment
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getGmtPayment() {
        return gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.gmt_payment
     *
     * @param gmtPayment the value for alipay_pay_trade_no.gmt_payment
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setGmtPayment(String gmtPayment) {
        this.gmtPayment = gmtPayment == null ? null : gmtPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.gmt_close
     *
     * @return the value of alipay_pay_trade_no.gmt_close
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getGmtClose() {
        return gmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.gmt_close
     *
     * @param gmtClose the value for alipay_pay_trade_no.gmt_close
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setGmtClose(String gmtClose) {
        this.gmtClose = gmtClose == null ? null : gmtClose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.seller_email
     *
     * @return the value of alipay_pay_trade_no.seller_email
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.seller_email
     *
     * @param sellerEmail the value for alipay_pay_trade_no.seller_email
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail == null ? null : sellerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.buyer_email
     *
     * @return the value of alipay_pay_trade_no.buyer_email
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.buyer_email
     *
     * @param buyerEmail the value for alipay_pay_trade_no.buyer_email
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.trade_status
     *
     * @return the value of alipay_pay_trade_no.trade_status
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.trade_status
     *
     * @param tradeStatus the value for alipay_pay_trade_no.trade_status
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.notify_url
     *
     * @return the value of alipay_pay_trade_no.notify_url
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.notify_url
     *
     * @param notifyUrl the value for alipay_pay_trade_no.notify_url
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.create_time
     *
     * @return the value of alipay_pay_trade_no.create_time
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.create_time
     *
     * @param createTime the value for alipay_pay_trade_no.create_time
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_pay_trade_no.update_time
     *
     * @return the value of alipay_pay_trade_no.update_time
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_pay_trade_no.update_time
     *
     * @param updateTime the value for alipay_pay_trade_no.update_time
     *
     * @mbggenerated Fri Apr 08 14:56:07 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}